### ISSUE TITLE
LogNorm curiosity

### ISSUE THREAD

**Issue by cjchristopher** [shchur/ifl-tpp#10]
Hi @shchur - my code is somewhat deviated from the repo as it currently stands, but we are still experiencing a few oddities. Notably - we are sometimes getting negative inter-event times when calling decoder.sample with the LogNormMix implementation.

Having dug around the codebase, I think I've found the problem, but I just wanted to verify!

Looking at the normal_sample https://github.com/shchur/ifl-tpp/blob/adb1dc72babc0821714bb226c7f77cf089ec552f/code/dpp/distributions/gaussian_mixture.py#L13-L17 as it is called in the _sample call, it seems that there isn't anything preventing a negative result if the sample drawn at Line 16 is negative, and the mean of the corresponding mixture component is positive enough, for small mixture components. Is my understanding of this presently correct?

**Comment by shchur** [comment]
We draw samples from a log-normal mixture distribution using the following procedure ([code](https://github.com/shchur/ifl-tpp/blob/adb1dc72babc0821714bb226c7f77cf089ec552f/code/dpp/decoders.py#L22), Section D.2 in the paper)
```
z_1 ~ GaussianMixture(...)
z_2 = a * z_1 + b
x = exp(z_2)
```
This corresponds to drawing a sample from a mixture of log-normal distributions. While `z_1` and `z_2` may be negative, `x` should always be positive after we apply the `exp` function. So I think the probably is likely in some other place.

**Comment by cjchristopher** [comment]
Thanks!
I was attempting to follow that through - 
So, decoder = LogNormMix = TransformedDist([Affine,Softplus], NormalMixture), following through the inheritance path.
TransformedDist.sample calls _sample, which is:
https://github.com/shchur/ifl-tpp/blob/45e8611e4048604218c3d60faab8735e8ada58d1/code/dpp/flows/transformed_distribution.py#L58-L69
Notable line 62 there is calling base_dist.sample - which the LogNorm call establishes as a NormalMixture, which resolves to the normal_sample snippet in my OP.

I note that the above snippet then pushes that sample through the two transforms - here it seems that Affine is using 1.0 for scale and 0 for shift, so no net change (with Trainable=false) - in any case, both forward passes multiple through the sample *after* exponentiation?

EDIT: Have left the above for posterity - I note that LogNormMix only uses Softplus when specified, otherwise uses Exp as the final transform, which I think is the case here - we still have negative samples being produced but I will continue to investigate.

**Comment by cjchristopher** [comment]
@shchur - we found our issue.
In the Exp flow here: https://github.com/shchur/ifl-tpp/blob/adb1dc72babc0821714bb226c7f77cf089ec552f/code/dpp/flows/exp.py#L10-L17

We are finding that occasionally we have very small inter-event times, such that after taking `x.exp()`, the magnitude is `<epsilon`, resulting in a negative return value
Can I ask what purpose the epsilon shift in the transform layer serves?

Cheers!

**Comment by shchur** [comment]
The main purpose of `epsilon` is to ensure that we never do `log(0)` in the `inverse` method. We also used `epsilon` in `forward` such that `forward` and `inverse` are actually inverses of each other. I guess you could safely change the line 15 to `y = x.exp()` and this should work fine.
