### ISSUE TITLE
Code for using context vector in the models

### ISSUE THREAD

**Issue by krsna6** [shchur/ifl-tpp#12]
@shchur - thank you so much for sharing the code, it is very readable and follows the paper closely. I was hoping you could give me pointers on how to incorporate the context vector $y_i$ in the models. This is described for the Yelp dataset in sec. F.3 in the paper but I was not able to find it in your codebase. 
Thanks again for your help!

**Comment by shchur** [comment]
Hi, sorry, the code that we used for that experiment was pretty ugly, so we haven't included it in the repo. It should be rather straightforward to implement it with the refactored version of the code, here is you can do it.
1. Add static attributes as argument to the [`Sequence` constructor](https://github.com/shchur/ifl-tpp/blob/master/code/dpp/data/sequence.py). Make sure that the `attributes` tensor has the same first dimension as `inter_times`, i.e. has shape `(seq_len, attr_dim)`.
2. In the [`Batch.from_list` method](https://github.com/shchur/ifl-tpp/blob/master/code/dpp/data/batch.py) stack the `attributes` vectors for each sequence into a padded tensor of shape `(batch_size, max_seq_len, attr_dim)` and store it as `batch.attributes`.
3. Combine the stacked/padded attributes (stored in `batch.attributes`) with the [context embedding](https://github.com/shchur/ifl-tpp/blob/e7ebab1ceab56cee440bd8e99b5c1bd42d6ada07/code/dpp/models/recurrent_tpp.py#L119) in the model. There are several ways you can do this. One idea is to create a new linear layer `self.attr_emb = nn.Linear(attr_dim, context_size)` in `RecurrentTPP.__init__` and change the [context computation](https://github.com/shchur/ifl-tpp/blob/e7ebab1ceab56cee440bd8e99b5c1bd42d6ada07/code/dpp/models/recurrent_tpp.py#L119) to `context = self.get_context(features) + self.attr_emb(batch.attributes)`.

**Comment by krsna6** [comment]
Thank you so much for the quick response. I appreciate it. I am working with your older code base in the branch `original-code` as it has other baselines too and it seems pretty straightforward to do this looks like.
