### ISSUE TITLE
on log likelihood misunderstanding

### ISSUE THREAD

**Issue by EDAPINENUT** [shchur/ifl-tpp#13]
In the log likelihood, there are two terms:
\lambda(\tau) and - \int_0^\tau \Lambda(s)ds
However, the first term in your code is calculated directedly use the inter_time_dist.log_prob() function, which is already the log of pdf, i.e. the sum of the two terms. And then the second term is calculated by log_survival_function again. I want to make sure if I misunderstood you, or it is an error.

**Comment by shchur** [comment]
You are correct that `log_prob()` computes log-intensity plus log survival probability (i.e., log intensity minus the integral). In the code ([lines 128-130](https://github.com/shchur/ifl-tpp/blob/e7ebab1ceab56cee440bd8e99b5c1bd42d6ada07/code/dpp/models/recurrent_tpp.py#L128)) I only compute the log survival probability for the time interval `[t_N, T)`, i.e. between the last event and the end of the observed time interval. Does this answer your question?

**Comment by EDAPINENUT** [comment]
Thanks. However, in lots of implementation, the final time interval survival probability is omitted, and do you agree that this can be all omitted, which will still be a strict model comparison.

**Comment by shchur** [comment]
I would be very careful when comparing to other implementations. Small changes (like rescaling / normalizing the times) can totally change the log-likelihood and make the results incomparable. I have also seen some implementations that compute the loss differently, like only computing the log-likelihood for marks, adding some regularization terms, or sometime even having serious bugs in the computation.

**Comment by EDAPINENUT** [comment]
Thanks a lot. I will continue following and expanding your fantastic work!
