### ISSUE TITLE
Implementation on missing data imputation

### ISSUE THREAD

**Issue by yugongg** [shchur/ifl-tpp#18]
Hi @shchur, thanks for releasing the code! I'm wondering if it is possible that you could provide the code for the section of missing data imputation - Sec. 5.4 & F.4 MISSING DATA IMPUTATION from your paper. 

I'm curious about your implementation of feeding imputations to the RNN. If keep your current framework, to include the imputations to be the history, the batch will keep changing and we need get_features(batch) & get_context(features) every time we have a new imputed event. This gives a very slow training process. Could you provide your implementation on this part, or give me some suggestions on implementing this 'training while imputing'?  Thanks!

**Comment by shchur** [comment]
Hi @yugongg. We looked for the code for this particular experiment but, unfortunately, it seems like we lost it somewhere between refactoring & moving from the internal repo to Github, I'm sorry about that :(

I can recommend having a look at this paper https://proceedings.mlr.press/v130/gupta21a.html that studies training of neural TPPs with automatically imputing the missing data in more detail. Here's the link to their code https://github.com/data-iitd/imtpp. I hope this helps.
