### ISSUE TITLE
How to get sequence embeddings?

### ISSUE THREAD

**Issue by zhh0998** [shchur/ifl-tpp#2]
Would you provide the code to get sequence embeddings? Or If it is already provided in the code, would you please let me know which part？It's would save me a lot of time. thanks

**Comment by shchur** [comment]
The code is already included in the library. I just pushed [a notebook](https://github.com/shchur/ifl-tpp/blob/master/code/generate_embeddings.ipynb) with an example of how to learn the sequence embeddings.
