### ISSUE TITLE
ATM dataset testing 

### ISSUE THREAD

**Issue by kiahsa2002** [shchur/ifl-tpp#7]
Hi,

I'm new to TPP.

I was trying to run your interactive ipython file with the ATM dataset as CSV file. I see all datasets you used are .npz.
 Do I have to preprocess ATM csv file to .npz? How you set the sequence length? Since the ATM dataset I have contains only 4 months of data. 

I request you to clarify.

Regards,
kiahsa

**Comment by shchur** [comment]
Hi, you can have a look at the way we store the data in npz files and convert your data accordingly. Here is a code snippet that allows you to do this:
```python
import numpy as np

loader = dict(np.load('data/stack_overflow.npz', allow_pickle=True))
print(loader.keys())
print(loader['arrival_times'])
print(loader['marks'])
```
Both `arrival_times` and `marks` are lists of lists. If you save your data to an `npz` file using the same format (using the function [`np.savez`](https://numpy.org/doc/stable/reference/generated/numpy.savez.html)), you should be able to load it with our function `dpp.data.load_dataset`.

**Comment by kiahsa2002** [comment]
Thank you for your response with details.



Regards,
Kiahsa
________________________________
