### ISSUE TITLE
How to get the expression of the distribution of inter-event time

### ISSUE THREAD

**Issue by xinyuesherry** [shchur/ifl-tpp#9]
Thanks for sharing the code and the excellent work. 

I am curious about how you plot Figure 9 and obtain the conditioned distribution of inter-event time? Is it possible for you to share your code of that part? Thanks in advance.

**Comment by suhasshrinivasan** [comment]
+1 Yes please, this would be really helpful. I too am interested in the same.

**Comment by shchur** [comment]
Hi, sorry, for some reason I missed the original question. I will publish a refactored implementation where this can be done much more easily in a few days. I will notify you once it's done.

**Comment by shchur** [comment]
@mengjingweilin, @suhasshrinivasan I have just pushed the [refactored version of the code](https://github.com/shchur/ifl-tpp/tree/refactor). Here is how you can get the inter-event distribution with the new version.

```python
# Define the model
model = dpp.models.LogNormMix(...)
# Train the model
...

# Select the sequence for which we would like to inspect the inter-event time distribution
idx = 1  # idx of the sequence that we are interested in
sequence = d_train[idx]
batch = dpp.data.Batch.from_list([sequence])

features = model.get_features(batch)
context = model.get_context(features)  # context vectors for all events, shape (1, seq_len, batch_size)
context_last = context[0, -1, :]  # context vector for the last event, shape (context_size,)

# Get the distribution over the last inter-event time - this is just a torch.distribution.Distribution
dist = model.get_inter_time_dist(context_last)

# Plot the PDF of the last inter-event time
import matplotlib.pyplot as plt
x = torch.linspace(1e-10, 10, 1000)
pdf = dist.log_prob(x).exp().detach().cpu()
plt.plot(x.cpu(), pdf)
```

**Comment by xinyuesherry** [comment]
@shchur Thanks for refactoring the code to be nice and clean. 
I noticed that this refactored version uses mark embedding instead of sequence embedding as features. 
Besides, the refactored version takes log(inter_times) and mark embedding as input to RNN to get context. However, the last version seems to concatenate RNN hidden state and sequence embeddings as context. 
Could you please elaborate more on these changes so that I can understand your code more?  Thanks in advance!

**Comment by shchur** [comment]
Hi, the older code did the same thing:
- [The RNN takes the log-interevent time](https://github.com/shchur/ifl-tpp/blob/adb1dc72babc0821714bb226c7f77cf089ec552f/code/dpp/nn.py#L78), (before this we [applied log to inter-event times](https://github.com/shchur/ifl-tpp/blob/adb1dc72babc0821714bb226c7f77cf089ec552f/code/dpp/data.py#L97))
- [Concatenates it with mark embedding, if there are marks](https://github.com/shchur/ifl-tpp/blob/adb1dc72babc0821714bb226c7f77cf089ec552f/code/dpp/nn.py#L85)

I call the input to the RNN as `features`, as you can see it's the same in both versions.

The `context` in the new version is defined as `rnn_output`. In the old version it was defined as concatenation of `rnn_output` and `sequence_embedding` (if sequence embedding is used). 
The `context` vector is what we use to obtain the parameters of the conditional distributions `p(inter_time | history)` and `p(mark | history)`, note that this is different from the `features` mentioned above.

The new version of the code does not support sequence embeddings yet, I was planning to add them later.

**Comment by shchur** [comment]
Hi @mengjingweilin and @suhasshrinivasan, I just realized that there was a serious bug that I introduced while refactoring. There was an off-by-one error that allowed the model to peek into the future, which means that the model produced completely garbage results. It is now [fixed](https://github.com/shchur/ifl-tpp/blob/cc96531d68a5ae5a509c9c60e9381e2b75bdd274/code/dpp/models/recurrent_tpp.py#L90).
